"""Initial API schema

Revision ID: 88fc1fdd1ed7
Revises: 
Create Date: 2025-06-26 14:02:22.657662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88fc1fdd1ed7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acknowledgment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('command',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('acc_x', sa.Float(), nullable=True),
    sa.Column('acc_y', sa.Float(), nullable=True),
    sa.Column('acc_z', sa.Float(), nullable=True),
    sa.Column('roll', sa.Float(), nullable=True),
    sa.Column('pitch', sa.Float(), nullable=True),
    sa.Column('yaw', sa.Float(), nullable=True),
    sa.Column('battery', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telemetry')
    op.drop_table('command')
    op.drop_table('acknowledgment')
    # ### end Alembic commands ###
